[package]
name = "storage"
version = "0.1.0"
edition = "2024"

[dependencies]
log.workspace = true

once_cell.workspace = true

sunset-async.workspace = true

embedded-storage.workspace = true
esp-storage.workspace = true
esp-hal.workspace = true
